# Generated by Django 4.1.1 on 2022-11-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_rename_country_district_delete_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
    ]
